### ISSUE TITLE
RadeonGPUProfiler fails to open captures of a specific Vulkan application

### ISSUE THREAD

**Issue by godlikepanos** [GPUOpen-Tools/Radeon-GPUProfiler#26] opened 2019-06-08 16:55 UTC
I've been trying to use RGP to profile my game engine but RGP fails to open the `rgp` capture files with the following message:

```
The profile failed to load. Do you want to remove the profile simple_scene-20190608-103033.rgp from the recent files list?
```

No more info than that. RGP seems to be working for some simple content (eg vulkan-smoketest) but not for my renderer.

I've uploaded an rgp file here if you want to check out: https://drive.google.com/file/d/1rafnjnSVO0lS3B0Dg3FlWNEhBepuKIgZ

Any idea what might be wrong?

System info:
OS: Ubuntu 18.04
kernel: 5.1.6
RGP: 1.5.1.7 (also fails on 1.4.1.39)
GPU: RX 580
Driver: AMDVLK, driverVersion: 8388699, "2019-5-24 update"

**Comment by mguerret-amd** [comment] 2019-06-10 14:40
Thanks for reporting this.

It looks like your provided google drive link if private. Is it possible to make the link public so that we can access the RGP file and reproduce your issue?

**Comment by godlikepanos** [comment] 2019-06-10 14:43
I'm very sorry. Can you check again?

**Comment by mguerret-amd** [comment] 2019-06-10 14:45
Yup, I've downloaded the trace. Thanks.

Will investigate further

**Comment by mguerret-amd** [comment] 2019-06-10 15:25
Was this captured from the simple-scene sample from anki 3D engine repo? If so, were you able to capture any RGP traces that were able to load correctly?

**Comment by godlikepanos** [comment] 2019-06-10 15:41
Correct, it's the simple_scene sample from AnKi. If you want to run it:
```
cd /path_to_checkout/samples/simple_scene
/path_to_build/bin/simple_scene -cfg window.fullscreen 0
```

Some months ago I was able to capture and view the simple_scene (and more complex AnKi demos) successfully. At the moment I cannot successfully view any of the captures of my demos. A lot have changed during the last time I used RGP. I'm using newer AMDVLK, newer RGP and AnKi's Vulkan backend enabled some new extensions.

Thank you a lot for looking into this!

**Comment by mguerret-amd** [comment] 2019-06-10 20:12
From initial investigation it appears to possibly be a driver issue. The following samples from the Sascha Willems Vulkan demo repository also fail with the same issue:
- bloom
- deferredmultisampling
- distancefieldfonts
- hdr
- multisampling
- multiview
- offscreen
- pbribl
- pbrtexture
- pipelines
- radialblur
- scenerendering
- shadowmapping
- tesselation

I've raised notice of this issue and hopefully it can be resolved soon.

**Comment by mguerret-amd** [comment] 2019-07-09 15:48
This should be fixed now in latest release of AMDVLK driver
[AMDVLK v-2019.Q3.1](https://github.com/GPUOpen-Drivers/AMDVLK/releases/tag/v-2019.Q3.1)

**Comment by godlikepanos** [comment] 2019-07-10 08:20
Thank you! I'll try to verify but at the moment that's a bit difficult because I'm experiencing some hangs (https://github.com/GPUOpen-Drivers/AMDVLK/issues/99).

Maybe it's better to close this ticket. I guess I can always reopen it if there are still issues.

**Closed** 2019-07-15 15:56 UTC
