### ISSUE TITLE
RGP source code

### ISSUE THREAD

**Issue by pemgithub** [GPUOpen-Tools/Radeon-GPUProfiler#32] opened 2019-11-15 23:26 UTC
Are there plans to post RGP source code here on GPUOpen-Tools?  I only see README / docs.

**Comment by shmerl** [comment] 2019-12-19 02:13
Dup of bug #1

**Comment by chesik-amd** [comment] 2020-03-06 19:03
Duplicate of #1

**Closed by chesik-amd** 2020-03-06 19:03 UTC
